/**
 * Integration check for AC-2: every committed `expected_names` entry in
 * `docs/retrieval-labeled-set.json` resolves to a memory `name` (canonical
 * filename) that exists in the in-repo user-scope corpus at
 * `~/.commonplace/memory/`. This catches dangling references where the
 * labeled set names a memory that has since been deleted or renamed.
 *
 * The check is best-effort: it skips when either the labeled set or the
 * user-scope corpus is not present (e.g. in CI environments that don't
 * have a populated `~/.commonplace/memory`).
 */

import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';

import { describe, expect, it } from 'vitest';

describe('docs/retrieval-labeled-set.json (ac-2)', () => {
  it('every expected_name resolves to an existing user-scope memory filename', () => {
    const labeledPath = join(__dirname, '..', 'docs', 'retrieval-labeled-set.json');
    const corpusDir = join(homedir(), '.commonplace', 'memory');

    if (!existsSync(labeledPath)) {
      // The labeled set is regenerated by the benchmark CLI; skip when
      // it hasn't been generated yet in this environment.
      return;
    }
    if (!existsSync(corpusDir)) {
      // No user-scope corpus available -- e.g. fresh CI runner. Skip.
      return;
    }

    const pairs = JSON.parse(readFileSync(labeledPath, 'utf8')) as Array<{
      query: string;
      expected_names: string[];
      category: string;
    }>;
    const corpusFilenames = new Set(
      readdirSync(corpusDir)
        .filter((f) => f.endsWith('.md'))
        .map((f) => f.replace(/\.md$/, '')),
    );

    expect(pairs.length).toBeGreaterThanOrEqual(1);
    for (const pair of pairs) {
      for (const name of pair.expected_names) {
        expect(corpusFilenames.has(name)).toBe(true);
      }
    }
  });
});
