/**
 * Integration check for AC-2: every committed `expected_names` entry in
 * `docs/retrieval-labeled-set.json` resolves to a memory `name` (canonical
 * filename) that exists in the in-repo user-scope corpus at
 * `~/.commonplace/memory/`. This catches dangling references where the
 * labeled set names a memory that has since been deleted or renamed.
 *
 * The check is best-effort: it skips when either the labeled set or the
 * user-scope corpus is not present (e.g. in CI environments that don't
 * have a populated `~/.commonplace/memory`).
 */

import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';

import { describe, expect, it } from 'vitest';

import type { LabeledPair } from '../scripts/build-labeled-set.js';

const isStringArray = (v: unknown): v is string[] =>
  Array.isArray(v) && v.every((n) => typeof n === 'string');

const isLabeledPairShape = (value: unknown): value is LabeledPair => {
  if (value === null || typeof value !== 'object') return false;
  const pair: Record<string, unknown> = { ...value };
  return (
    typeof pair.query === 'string' &&
    isStringArray(pair.expected_names) &&
    typeof pair.category === 'string'
  );
};

const isLabeledPairArray = (value: unknown): value is LabeledPair[] =>
  Array.isArray(value) && value.every(isLabeledPairShape);

describe('docs/retrieval-labeled-set.json (ac-2)', () => {
  it('every expected_name resolves to an existing user-scope memory filename', () => {
    const labeledPath = join(__dirname, '..', 'docs', 'retrieval-labeled-set.json');
    const corpusDir = join(homedir(), '.commonplace', 'memory');

    if (!existsSync(labeledPath)) {
      // The labeled set is regenerated by the benchmark CLI; skip when
      // it hasn't been generated yet in this environment.
      return;
    }
    if (!existsSync(corpusDir)) {
      // No user-scope corpus available -- e.g. fresh CI runner. Skip.
      return;
    }

    const parsed: unknown = JSON.parse(readFileSync(labeledPath, 'utf8'));
    if (!isLabeledPairArray(parsed)) {
      throw new Error(
        'docs/retrieval-labeled-set.json failed shape validation: expected an array ' +
          'of { query: string; expected_names: string[]; category: string } entries. ' +
          'The labeled-set schema may have drifted; re-run scripts/run-retrieval-benchmark.ts.',
      );
    }
    const pairs = parsed;
    const corpusFilenames = new Set(
      readdirSync(corpusDir)
        .filter((f) => f.endsWith('.md'))
        .map((f) => f.replace(/\.md$/, '')),
    );

    expect(pairs.length).toBeGreaterThanOrEqual(1);
    for (const pair of pairs) {
      for (const name of pair.expected_names) {
        expect(corpusFilenames.has(name)).toBe(true);
      }
    }
  });
});
